# Generated by Django 6.0.3 on 2026-03-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_usuario_delete_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tefone',
            new_name='telefone',
        ),
    ]
