# Generated by Django 6.0.3 on 2026-03-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_rename_tefone_usuario_telefone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
